Topic : Numpy Assignment

# 1. What is a Python library? Why do we use Python libraries?

Answer : A Python library is pre-written , reusable , well tested code which can utilized by any python developer to perform similar task.
    
we used the python libraries because of code reusablity , Productivity , efficiency , well tested code , standarization and hence save time with use of python library.

# 2. What is the difference between Numpy array and List?

Answer : Difference between Numpy array and List

1) Numpy array contain all element of same data type while List can contain elements of different data type

2) Since NumPy uses asame data-type means fixed type array which allows for better memory management and storage of large datasets.
 while list may be of different data type which requiring additional memory overhead.And hence, Numpy array are more memory efficient than list.
    
3) Numpy array operation are faster while List numerical operations are slower for large dataset.

4) Numpy array can be of multi dimensional while list is one dimensional.

# 3. Find the shape, size and dimension of the following array?

[[1, 2, 3, 4] ,
[5, 6, 7, 8],
[9,10,11,12]]


In [5]:
l = [[1, 2, 3, 4] ,
[5, 6, 7, 8],
[9,10,11,12]]

In [6]:
type(l)

list

In [8]:
import numpy as np

Converting the given list to numpy array

In [9]:
a = np.array(l)

In [10]:
type(a)

numpy.ndarray

Shape of array

In [11]:
a.shape

(3, 4)

Size of array

In [13]:
a.size

12

Dimension of array

In [14]:
a.ndim

2

# 4. Write python code to access the first row of the following array?

[[1, 2, 3, 4],
[5, 6, 7, 8],
[9,10,11,12]]


Note: in question 3, we are using same numpy array so we can use same variable a

In [17]:
a[0]

array([1, 2, 3, 4])

# 5. How do you access the element at the third row and fourth column from the given numpy array?

[[1, 2, 3, 4]
[5, 6, 7, 8],
[9,10,11,12]]

Note: in question 3, we are using same numpy array so we can use same variable a

For entire 3rd row of the above array

In [18]:
a[2]

array([ 9, 10, 11, 12])

For 3rd rown and 4th column of the array

In [19]:
a[2][3]

12

# 6. Write code to extract all odd-indexed elements from the given array
[[1, 2, 3, 4]
[5, 6, 7, 8],
[9,10,11,12]]


In [20]:
a

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

Create empty list to store required item ( odd indexed elements)

In [22]:
odd_indexed_elements = []

For each row and column index check if it's odd , extract the elements and append it to the list

In [23]:
for row_index , rows in enumerate(a):
    for col_index , item in enumerate(rows):
        if row_index %2 == 1 and col_index %2 == 1 :
            odd_indexed_elements.append(item)
            

In [25]:
print("all odd-indexed elements from the given array : " , odd_indexed_elements)

all odd-indexed elements from the given array :  [6, 8]


# 7. How can you generate a random 3*3 matrix with values between 0 and 1?


To get random number between 0 and 1 , use random.random

In [32]:
 b = np.random.random(size = ( 3, 3))

In [33]:
b

array([[0.20125108, 0.17487596, 0.16172589],
       [0.70714264, 0.48062433, 0.87596703],
       [0.97084239, 0.63728801, 0.56385239]])

In [37]:
type(b)

numpy.ndarray

In [34]:
c = np.matrix(b)

In [35]:
c

matrix([[0.20125108, 0.17487596, 0.16172589],
        [0.70714264, 0.48062433, 0.87596703],
        [0.97084239, 0.63728801, 0.56385239]])

In [36]:
type(c)

numpy.matrix

# 8. Describe the difference between np.random.rand and np.random.randn ?

np.random.rand : Create an array of the given shape and populate it with random samples from a uniform distribution over [0, 1).

In [38]:
np.random.rand(3,2)

array([[0.09394072, 0.80613176],
       [0.38389948, 0.22848036],
       [0.55910637, 0.75441509]])

np.random.randn : Return a sample from the “standard normal” distribution

If arguments are provided, randn generates an array of shape (d0, d1, ..., dn), filled with random floats sampled from a univariate “normal” distribution of mean 0 and variance 1. 

A single float randomly sampled from the distribution is returned if no argument is provided.

In [39]:
np.random.randn()

0.8401169985872847

In [42]:
np.random.randn(2,3)

array([[-1.6026493 ,  0.80883828,  0.95139686],
       [ 1.52024418, -0.62195975, -0.38919556]])

For random samples from the normal distribution with mean m and standard deviation sd , we use

sd * np.random.randn(...) + m

Two-by-three array of samples from the normal distribution with mean 5 and standard deviation 1,5

In [43]:
1.5 * np.random.randn(2, 3) + 5

array([[ 7.55247455,  4.17638721,  8.27450308],
       [10.55047116,  6.17531795,  4.39788655]])

# 9. Write code to increase the dimension of the following array?

[[1,2,3,4] ,
 [5,6,7,8] ,
 [9,10,111,12]]

Note: in question 3, we are using same numpy array so we can use same variable a

In [44]:
a

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [45]:
a.ndim

2

Expand the shape of an array by using np.expand_dims

In [56]:
b = np.expand_dims(a,axis =0)

In [57]:
b

array([[[ 1,  2,  3,  4],
        [ 5,  6,  7,  8],
        [ 9, 10, 11, 12]]])

In [58]:
b.ndim

3

In [ ]:
Note: we can also add a New Axis to a Numpy Array

In [61]:
c = a[: , : , np.newaxis]

In [62]:
c

array([[[ 1],
        [ 2],
        [ 3],
        [ 4]],

       [[ 5],
        [ 6],
        [ 7],
        [ 8]],

       [[ 9],
        [10],
        [11],
        [12]]])

In [63]:
c.ndim

3

# 10. How to transpose the following array in NumPy? 

[[1, 2, 3, 4]
[5, 6, 7, 8],
[9,10,11,12]]


Note: in question 3, we are using same numpy array so we can use same variable a

In [64]:
a

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

Transpose the array by using 'T' function

In [65]:
a.T

array([[ 1,  5,  9],
       [ 2,  6, 10],
       [ 3,  7, 11],
       [ 4,  8, 12]])

# 11. Consider the following matrix:
    
Matrix A: [[1, 2, 3, 4] [5, 6, 7, 8],[9,10,11,12]]
Matrix B: [[1, 2, 3, 4] [5, 6, 7, 8],[9,10,11,12]]

Perform the following operation using Python:
1.	Index wise multiplication
2.	Matrix multiplication
3.	Add both the metrics
4.	Subtract matrix B from A
5.	Divide Matrix B by A


In [67]:
A = np.array([[1, 2, 3, 4] , [5, 6, 7, 8],[9,10,11,12]])

In [68]:
A

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [69]:
type(A)

numpy.ndarray

In [70]:
B = np.array([[1, 2, 3, 4] ,[5, 6, 7, 8],[9,10,11,12]])

In [71]:
B

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [72]:
type(B)

numpy.ndarray

a) Index wise multiplication

In [73]:
A * B

array([[  1,   4,   9,  16],
       [ 25,  36,  49,  64],
       [ 81, 100, 121, 144]])

b) Matrix multiplication

In [76]:
A.shape

(3, 4)

In [77]:
B.shape

(3, 4)

For Maxtrix multiplication , number of column in first matrix should be equal to number of rows in second matrix. So, we will transpose the second matrix for matrix multiplication

In [75]:
A @ B.T

array([[ 30,  70, 110],
       [ 70, 174, 278],
       [110, 278, 446]])

c) Add both the metrics

In [78]:
A + B

array([[ 2,  4,  6,  8],
       [10, 12, 14, 16],
       [18, 20, 22, 24]])

d) Subtract matrix B from A

In [79]:
A - B

array([[0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0]])

e) Divide Matrix B by A

In [80]:
B/A

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

# 12. Which function in Numpy can be used to swap the byte order of on array?

In [ ]:
Anser of the question is byteswap function

In [92]:
a = np.array([1,2,3,4])

In [93]:
a

array([1, 2, 3, 4])

In [94]:
b = a.byteswap()

In [95]:
b

array([16777216, 33554432, 50331648, 67108864])

However there are two ways you can affect the relationship between the byte ordering of the array and the underlying memory it is looking at:

newbyteorder : Change the byte-ordering information in the array dtype so that it interprets the underlying data as being in a different byte order. This is the role of arr.newbyteorder()

byteswap : Change the byte-ordering of the underlying data, leaving the dtype interpretation as it was. This is what arr.byteswap() does.

# 13. What is the significance of the np.IinaIg.inv function?

The np.linalg.inv function is used to compute the (multiplicative) inverse of a matrix. 

When a matrix A and np.linalg.inv(A) is multplied ,it gives the identity matrix

In [108]:
C = np.array([[1., 2.], [3., 4.]])

In [109]:
C

array([[1., 2.],
       [3., 4.]])

In [110]:
D = np.linalg.inv(C)

In [111]:
D

array([[-2. ,  1. ],
       [ 1.5, -0.5]])

In [115]:
np.dot(C,D)

array([[1.00000000e+00, 1.11022302e-16],
       [0.00000000e+00, 1.00000000e+00]])

# 14. What does the np.reshape function do, and how is it used?

np.reshape :
    
Reshaping means changing the shape of an array.The shape of an array is the number of elements in each dimension.By reshaping we can add or remove dimensions or change number of elements in each dimension.

In [116]:
k = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12])


In [117]:
k

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [120]:
k.shape

(12,)

In [118]:
n = k.reshape(4, 3)


In [119]:
n

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [121]:
n.shape

(4, 3)

# 15. What is broadcasting in Numpy?

numpy operations are usually done element-by-element which requires two arrays to have exactly the same shape:If the dimensions of two arrays are dissimilar, element-to-element operations are not possible.

Broadcasting is a powerful feature in NumPy that allows for performing operations on arrays of different shapes and sizes. NumPy automatically broadcasts the smaller array to match the shape of the larger array, making it possible to perform element-wise operations even when the arrays have different shapes.

The broadcasting rules in NumPy are designed to work with arrays of different shapes, following these steps:

If the arrays do not have the same number of dimensions:Pad the smaller-dimensional array's shape on its left side with ones until both shapes have the same length.

If the sizes of the dimensions don't match:If a dimension size is 1 in one of the arrays, the array is broadcasted along that dimension to match the size of the other array.

The simplest broadcasting example occurs when an array and a scalar value are combined in an operation:

In [124]:
a

array([1, 2, 3, 4])

In [125]:
a * 5 

array([ 5, 10, 15, 20])